### ISSUE TITLE
level2 리뷰

### ISSUE THREAD

**Issue by hanjungeun0909** [hyun1024/springlv2project#6]
userservice 에서  @Size @Pattern 을 사용하지 않고 username과 password의 구성을 제한 하는게 참신하네요.
지금은 작성시간 순서대로 데이터가 쌓이기 때문에 목록을 불러올때 순서대로 불러오지만, 구체적인 jpa명령어를 사용하는건 어떻까 싶습니다. 
필터부분 잘보고 갑니다~

**Comment by hyun1024** [comment]
정규식 필터의 위치에 따른 장점과 문제점 찾아보기. 서비스의 요구 사항 체크하기
선택한 게시글 조회하기의 다양한 기능(ex.글 하나만 찾기, n번째 글 찾기)에 대해 생각해보기.
좋은 리뷰 감사합니다!
